language: python


python:
   - 3.5

install:
   - pip install pytest-cov
   - pip install python-coveralls

script:
   - py.test --cov-report= --cov=rpn test_rpn.py
   - make test


after_success:
  - coveralls
